"""empty message

Revision ID: 99c684a84baa
Revises: 
Create Date: 2024-04-07 17:53:44.898560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c684a84baa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersdata_hashed_password'), 'usersdata', ['hashed_password'], unique=True)
    op.create_index(op.f('ix_usersdata_id'), 'usersdata', ['id'], unique=False)
    op.create_index(op.f('ix_usersdata_username'), 'usersdata', ['username'], unique=True)
    op.drop_table('details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alternate_contact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('addline1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('addline2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='details_pkey')
    )
    op.drop_index(op.f('ix_usersdata_username'), table_name='usersdata')
    op.drop_index(op.f('ix_usersdata_id'), table_name='usersdata')
    op.drop_index(op.f('ix_usersdata_hashed_password'), table_name='usersdata')
    op.drop_table('usersdata')
    # ### end Alembic commands ###
