# Generated by Django 3.2.12 on 2024-05-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='student_table',
        ),
    ]
