# Generated by Django 3.2.12 on 2024-05-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_students_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='Student Info',
        ),
    ]
