# Generated by Django 3.2.12 on 2024-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_alter_students_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stud_gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
