# Generated by Django 3.2.12 on 2024-05-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_students_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
