# Generated by Django 3.2.12 on 2024-05-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_students_stud_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
