"""empty message

Revision ID: 3c9cce4a7caf
Revises: 1b9350351deb
Create Date: 2024-05-22 07:01:43.534306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c9cce4a7caf'
down_revision: Union[str, None] = '1b9350351deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.drop_table('RepostMail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RepostMail',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"RepostMail_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Organization', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='RepostMail_pkey')
    )
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
