# Generated by Django 3.2.12 on 2024-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_rollno', models.IntegerField()),
                ('student_total', models.ImageField(max_length=10, upload_to='')),
            ],
        ),
    ]
